# Generated by Django 4.2.4 on 2023-08-17 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('wallet_type', models.CharField(blank=True, max_length=50, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=100, null=True)),
                ('usdt_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile')),
            ],
        ),
    ]
