# Generated by Django 4.2.4 on 2023-08-25 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('deposit', '0002_alter_deposit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='time',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='userprofile.profile'),
        ),
    ]
