# Generated by Django 4.2.4 on 2023-09-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0004_alter_deposit_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='wallet_address',
            field=models.CharField(blank=True, choices=[('USDT', 'USDT'), ('LTC', 'Litecoin'), ('BTC', 'Bitcoin'), ('XRP', 'XRP'), ('ETH', 'ETHERUM')], max_length=100, null=True),
        ),
    ]
