# Generated by Django 4.2.4 on 2023-08-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_address', models.CharField(blank=True, max_length=200, null=True)),
                ('litecoin_address', models.CharField(blank=True, max_length=200, null=True)),
                ('xrp_address', models.CharField(blank=True, max_length=200, null=True)),
                ('etherum_address', models.CharField(blank=True, max_length=200, null=True)),
                ('usdt_address', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(default='Wallet Address', max_length=100)),
            ],
        ),
    ]
