# Generated by Django 4.2.4 on 2023-09-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmentplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
