# Generated by Django 4.2.4 on 2023-09-02 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_remove_profile_user_plan'),
        ('investmentplan', '0004_delete_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentplanhistory',
            name='investment_profit_percent',
        ),
        migrations.RemoveField(
            model_name='investmentplanhistory',
            name='maximum_amount',
        ),
        migrations.RemoveField(
            model_name='investmentplanhistory',
            name='minimum_amount',
        ),
        migrations.RemoveField(
            model_name='investmentplanhistory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='investmentplanhistory',
            name='number_of_days',
        ),
        migrations.RemoveField(
            model_name='investmentplanhistory',
            name='referral_profit_percent',
        ),
        migrations.AddField(
            model_name='investmentplanhistory',
            name='investmentplan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='investmentplan.investmentplan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentplanhistory',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='userprofile.profile'),
            preserve_default=False,
        ),
    ]
