# Generated by Django 4.2.4 on 2023-09-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_referral_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='created',
        ),
    ]
