# Generated by Django 4.2.4 on 2023-09-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['-created'], 'verbose_name': 'Bonus', 'verbose_name_plural': 'Bonuses'},
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='username',
        ),
    ]
