# Generated by Django 4.2.4 on 2023-09-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.CharField(blank=True, choices=[('usdt', 'USDT'), ('ltc', 'Litecoin'), ('btc', 'Bitcoin'), ('xrp', 'XRP'), ('etherum', 'ETHERUM')], max_length=100, null=True),
        ),
    ]
