# Generated by Django 4.2.4 on 2023-09-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0003_alter_withdrawal_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet_type',
            field=models.CharField(blank=True, choices=[('USDT', 'USDT'), ('LTC', 'Litecoin'), ('BTC', 'Bitcoin'), ('XRP', 'XRP'), ('ETH', 'ETHERUM')], max_length=10, null=True),
        ),
    ]
