# Generated by Django 4.2.4 on 2023-09-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runingdays', models.IntegerField(blank=True, null=True)),
                ('extradeposit', models.IntegerField(blank=True, null=True)),
                ('extrawithdrawal', models.IntegerField(blank=True, null=True)),
                ('extrausers', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
