# Generated by Django 4.2.4 on 2023-08-25 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('usdt_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('verified', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_made', to='userprofile.profile')),
                ('transfer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='userprofile.profile')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
