# Generated by Django 4.2.4 on 2023-09-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='verified',
            new_name='transferred',
        ),
    ]
