# Generated by Django 4.2.4 on 2023-09-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_rename_verified_transfer_transferred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='amount',
        ),
    ]
