# Generated by Django 4.2.4 on 2023-09-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_rename_plan_profile_user_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_plan',
        ),
    ]
