# Generated by Django 4.2.4 on 2023-09-02 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investmentplan', '0005_remove_investmentplanhistory_investment_profit_percent_and_more'),
        ('userprofile', '0005_alter_profile_user'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='investment_profit_percent',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='number_of_days',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='referral_profit_percent',
        ),
        migrations.AddField(
            model_name='plan',
            name='investmentplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investmentplan', to='investmentplan.investmentplan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile'),
        ),
    ]
