# Generated by Django 4.2.4 on 2023-09-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_remove_plan_investment_profit_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
