# Generated by Django 4.2.4 on 2023-09-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_alter_plan_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
