# Generated by Django 4.2.4 on 2023-08-27 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kyc',
            options={'ordering': ['-created'], 'verbose_name': 'Kyc', 'verbose_name_plural': 'Kyc'},
        ),
        migrations.AddField(
            model_name='kyc',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
